from pydicom import dcmread
path = 'INPUT/IM-0001-0001.dcm'
ds =dcmread(path)
print(ds)
sn=" \n"
patientname = str(ds.PatientName)
patientid= str(ds.PatientID)
patientbirthdate=str(ds[0x10,0x30].value)
patientsex=str(ds.PatientSex)
institutionname = str(ds.InstitutionName)
institutionaddress =str(ds.InstitutionAddress)
physicianname= str(ds.ReferringPhysicianName)
studydiscription=str(ds.StudyDescription)
modality = str(ds.Modality)
manufacturer = str(ds.Manufacturer)
studyid = str(ds[0x20, 0x10].value)
studydate=str(ds[0x8,0x20].value)
seriesnumber=str(ds[0x20,0x11].value)
pixelspacingx=str(ds[0x28,0x30][0])
pixelspacingy=str(ds[0x28,0x30][1])
slicethickness=str(ds[0x18,0x50].value)
columns=str(ds[0x28,0x10].value)
rows=str(ds[0x28,0x11].value)
patientposition=str(ds[0x18,0x5100].value)
imageorientationpatientrowx=str(ds[0x20,0x37][0])
imageorientationpatientrowy=str(ds[0x20,0x37][1])
imageorientationpatientrowz=str(ds[0x20,0x37][2])
imageorientationpatientcolumnx=str(ds[0x20,0x37][3])
imageorientationpatientcolumny=str(ds[0x20,0x37][4])
imageorientationpatientcolumnz=str(ds[0x20,0x37][5])
patientinfo=patientname+sn+patientid+sn+patientbirthdate+sn+patientsex+sn
institutioninfo=institutionname+sn+institutionaddress+sn+physicianname+sn+studydiscription+sn
modalityinfo=modality+sn+manufacturer+sn
imageinfo=studyid+sn+studydate+sn+seriesnumber+sn+pixelspacingx+sn+pixelspacingy+sn+slicethickness+sn+columns+sn+rows+sn+patientposition+sn+imageorientationpatientrowx+sn+imageorientationpatientrowy+sn+imageorientationpatientrowz+sn+imageorientationpatientcolumnx+sn+imageorientationpatientcolumny+sn+imageorientationpatientcolumnz
output = patientinfo + institutioninfo + modalityinfo + imageinfo
print(output, file = open('OUTPUT/VisibleHumanMale.txt', 'w'))
